# Basics of numpy

Simple ways to create, view, and manipulate arrays

Links to documentation and other examples
http://www.numpy.org/


## Python Data Science Handbook
http://nbviewer.jupyter.org/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.00-Introduction-to-NumPy.ipynb

I've copied and pasted just a few examples below.  Please read the entire chapter for more

In [2]:
import numpy as np

In [3]:
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\msd97m\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\msd97m\appdata\local\continuum\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <http://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <http://ipython.scipy.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are 

You can also use tab completion to see what you get.  Type "np." then press tab to see options 

In [4]:
np.

SyntaxError: invalid syntax (<ipython-input-4-c7736c2a1d14>, line 1)

Creating Arrays from Scratch

Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy. Here are several examples:

In [5]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [7]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [8]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [10]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[ 0.62072732,  0.53132442,  0.04525087],
       [ 0.25448137,  0.9227191 ,  0.74581531],
       [ 0.78822257,  0.67782195,  0.95868369]])

In [11]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.77922614,  0.47520387,  1.55105199],
       [-0.16620334,  1.1630342 , -1.14184054],
       [-0.50966479, -0.54209442, -0.65287733]])

Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array):

In [13]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)



x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [14]:
x1

array([6, 9, 8, 7, 2, 4])

In [15]:
x1[0]

6

To index from the end of the array, you can use negative indices:

In [16]:
x1[-1]

4

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [17]:
x2

array([[7, 9, 8, 1],
       [3, 4, 2, 8],
       [0, 8, 6, 2]])

In [18]:
x2[0, 0]

7

In [19]:
x2[2, -1]


2


### Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this:

x[start:stop:step]

If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1. We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.


In [21]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [28]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [29]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [30]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [31]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

A potentially confusing case is when the step value is negative. In this case, the defaults for start and stop are swapped. This becomes a convenient way to reverse an array:

In [32]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

We get useful functions like: sum, prod, mean, std, var, min, max, median, and percentile


In [33]:
x.sum()

45

In [34]:
x.mean()

4.5